### ISSUE TITLE
Cleanup tooltips

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/webclades#33]
Each tooltip should only show information which pertains to the tooltip's target.

The tooltip  for sequence name column should gather all these pieces together.

**Comment by rneher** [comment]
Whether we want to gather everything in a tooltip on the sequence name or add multiple tooltips for the QC, non-ACGT, gap, N columns is up for discussion. These individual tooltips would be less cluttered and would have only one type of info.
