### ISSUE TITLE
Make a releasable draft of the "about" section

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/webclades#42]
I made a terrible mess there, @rneher could you please clean this up and prepare for the end-user's eyes:
https://github.com/neherlab/webclades/blob/feat/landing/packages/web/src/components/About/AboutContent.mdx

**Comment by rneher** [comment]
this is mostly addressed in https://github.com/neherlab/webclades/commit/ffcc3690c5fa9448276408d0ee3bfc0f7b3a49c7
